import { Noto_Color_Emoji, Space_Grotesk } from "next/font/google";
import "./globals.css";

const emojiFont = Noto_Color_Emoji({
  weight: ["400"],
  subsets: ["emoji"],
  variable: "--emoji-font",
});
const fontSans = Space_Grotesk({
  subsets: ["latin"],
  weight: ["700", "400"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={[fontSans.className, emojiFont.variable].join(" ")}
    >
      <body>{children}</body>
    </html>
  );
}
